@host = http://localhost
@port = 5160

@RoomReservation.API_HostAddress = https://localhost:7073


###

GET {{RoomReservation.API_HostAddress}}/api/clients


###

@id=3
GET {{RoomReservation.API_HostAddress}}/api/clients/{{id}}

###


POST {{RoomReservation.API_HostAddress}}/api/clients
Content-Type: application/json

{
  "Name": "ClientX"
}

###

GET {{RoomReservation.API_HostAddress}}/api/bookings

###


GET {{RoomReservation.API_HostAddress}}/api/bookings/getreservations
Content-Type: application/json
clientId: 2

{
    "ExternalService" : "google"
}
###
