@host = http://localhost
@port = 5160

@RoomReservation.API_HostAddress = https://localhost:7073


###

GET {{RoomReservation.API_HostAddress}}/api/clients


###

@id=1
GET {{RoomReservation.API_HostAddress}}/api/clients/{{id}}

###


POST {{RoomReservation.API_HostAddress}}/api/clients
Content-Type: application/json

{
  "Name": "ClientX"
}

###

GET {{RoomReservation.API_HostAddress}}/api/bookings

###

// get with google
GET {{RoomReservation.API_HostAddress}}/api/bookings/getreservations
Content-Type: application/json
clientId: 1

{
     
    "startTime": "2024-12-10T08:59:00Z", 
    "endTime": "2024-12-10T10:30:00Z",
    "externalService" : "google"
}
###

// get with ms365
GET {{RoomReservation.API_HostAddress}}/api/bookings/getreservations
Content-Type: application/json
clientId: 2

{
     
    "externalService" : "ms365"
}
###

// get with default
GET {{RoomReservation.API_HostAddress}}/api/bookings/getreservations
Content-Type: application/json
clientId: 3

{
     
    "externalService" : ""
}
###

// get with unknown service
GET {{RoomReservation.API_HostAddress}}/api/bookings/getreservations
Content-Type: application/json
clientId: 1

{
     
    "externalService" : "xyz"
}
###


//overlap request
POST {{RoomReservation.API_HostAddress}}/api/bookings
Content-Type: application/json
clientId: 1

{
    "startTime": "2025-01-04T14:00:00Z", 
    "endTime": "2025-01-04T15:00:00Z", 
    "title": "Team Meeting", 
    "roomId": "5", 
    "externalService" : "google"
}

###

//clientId Invalid format request 
POST {{RoomReservation.API_HostAddress}}/api/bookings
Content-Type: application/json
clientId: "abc"

{
    "startTime": "2025-01-04T14:00:00Z", 
    "endTime": "2025-01-04T15:00:00Z", 
    "title": "Team Meeting", 
    "roomId": "5", 
    "externalService" : "google"
}

###


//clientId Invalid value request 
POST {{RoomReservation.API_HostAddress}}/api/bookings
Content-Type: application/json
clientId: 12345

{
    "startTime": "2025-01-04T14:00:00Z", 
    "endTime": "2025-01-04T15:00:00ZS", 
    "title": "Team Meeting", 
    "roomId": "15", 
    "externalService" : "google"
}

###

// Valid request - change room Id
POST {{RoomReservation.API_HostAddress}}/api/bookings
Content-Type: application/json
clientId: 1

{
    "startTime": "2025-01-04T15:00:00Z", 
    "endTime": "2025-01-04T16:00:00Z", 
    "title": "Team Meeting", 
    "roomId": "51", 
    "externalService" : "google"
}

###
